// <auto-generated/>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pico.Infrastructure.Persistence;

#nullable disable

namespace Pico.Infrastructure.Persistence.Migrations
{
    /// <summary>EF Core model snapshot for PicoDbContext (manually written since design-time tooling isn't set up in CI).</summary>
    [DbContext(typeof(PicoDbContext))]
    partial class PicoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity("Pico.Domain.Entities.Flavor", b =>
            {
                b.Property<Guid>("Id");
                b.Property<string>("Category");
                b.Property<int>("DiskGb");
                b.Property<string>("Name");
                b.Property<decimal>("PricePerHour");
                b.Property<decimal>("PricePerMonth");
                b.Property<int>("RamMb");
                b.Property<int>("Vcpus");
                b.Property<bool>("Active");
                b.HasKey("Id");
                b.ToTable("flavors");
            });

            modelBuilder.Entity("Pico.Domain.Entities.Image", b =>
            {
                b.Property<Guid>("Id");
                b.Property<string>("Name");
                b.Property<string>("Os");
                b.Property<int>("SizeGb");
                b.Property<string>("Version");
                b.Property<bool>("Active");
                b.HasKey("Id");
                b.ToTable("images");
            });

            modelBuilder.Entity("Pico.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id");
                b.Property<DateTimeOffset>("CreatedAt");
                b.Property<string>("Email");
                b.Property<string>("Name");
                b.Property<string>("PasswordHash");
                b.Property<string>("Role");
                b.HasKey("Id");
                b.ToTable("users");
            });

            modelBuilder.Entity("Pico.Domain.Entities.Resource", b =>
            {
                b.Property<Guid>("Id");
                b.Property<DateTimeOffset>("CreatedAt");
                b.Property<string>("ExternalId");
                b.Property<Guid>("FlavorId");
                b.Property<Guid>("ImageId");
                b.Property<string>("IpAddress");
                b.Property<string>("Name");
                b.Property<string>("Status");
                b.Property<DateTimeOffset>("UpdatedAt");
                b.Property<Guid>("UserId");
                b.HasKey("Id");
                b.ToTable("resources");
                b.HasOne("Pico.Domain.Entities.Flavor", null).WithMany().HasForeignKey("FlavorId").OnDelete(DeleteBehavior.Restrict);
                b.HasOne("Pico.Domain.Entities.Image", null).WithMany().HasForeignKey("ImageId").OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("Pico.Domain.Entities.ResourceEvent", b =>
            {
                b.Property<Guid>("Id");
                b.Property<string>("EventType");
                b.Property<string>("Message");
                b.Property<string>("NewStatus");
                b.Property<string>("OldStatus");
                b.Property<Guid>("ResourceId");
                b.Property<DateTimeOffset>("Timestamp");
                b.HasKey("Id");
                b.ToTable("resource_events");
            });

            modelBuilder.Entity("Pico.Domain.Entities.Invoice", b =>
            {
                b.Property<Guid>("Id");
                b.Property<DateTimeOffset>("CreatedAt");
                b.Property<DateTimeOffset?>("PaidAt");
                b.Property<DateTimeOffset>("PeriodEnd");
                b.Property<DateTimeOffset>("PeriodStart");
                b.Property<decimal>("Total");
                b.Property<string>("Status");
                b.Property<Guid>("UserId");
                b.HasKey("Id");
                b.ToTable("invoices");
            });

            modelBuilder.Entity("Pico.Domain.Entities.InvoiceLine", b =>
            {
                b.Property<decimal>("Amount");
                b.Property<string>("Description");
                b.Property<Guid>("FlavorId");
                b.Property<decimal>("Hours");
                b.Property<Guid>("Id");
                b.Property<Guid>("InvoiceId");
                b.Property<decimal>("Rate");
                b.Property<Guid>("ResourceId");
                b.HasKey("Id");
                b.ToTable("invoice_lines");
            });

            modelBuilder.Entity("Pico.Domain.Entities.AuditLog", b =>
            {
                b.Property<string>("Action");
                b.Property<string>("DetailsJson");
                b.Property<Guid?>("EntityId");
                b.Property<string>("EntityType");
                b.Property<Guid>("Id");
                b.Property<DateTimeOffset>("Timestamp");
                b.Property<Guid?>("UserId");
                b.HasKey("Id");
                b.ToTable("audit_logs");
            });
        }
    }
}
